import { query } from './db';
import { hashPassword } from './password';

const customerProfiles = [
  [
    '北京恒信档案科技有限公司',
    '恒信档案',
    '企业',
    '档案数字化',
    '010-68561234',
    '北京',
    '行业交流',
    '重点',
  ],
  [
    '上海启明城市建设发展有限公司',
    '启明城建',
    '企业',
    '智慧城市',
    '021-58346721',
    '上海',
    '合作伙伴',
    '普通',
  ],
  [
    '深圳远洋文化传媒集团有限公司',
    '远洋传媒',
    '企业',
    '文化传媒',
    '0755-82931678',
    '深圳',
    '官网咨询',
    '重点',
  ],
  [
    '杭州市档案馆',
    '杭州档案馆',
    '政府',
    '档案管理',
    '0571-87051268',
    '杭州',
    '行业交流',
    '重点',
  ],
  [
    '广州南粤教育发展中心',
    '南粤教育',
    '事业单位',
    '教育服务',
    '020-38910542',
    '广州',
    '转介绍',
    '潜在',
  ],
  [
    '成都锦城文旅发展有限公司',
    '锦城文旅',
    '企业',
    '文旅产业',
    '028-86751209',
    '成都',
    '展会获客',
    '重点',
  ],
  [
    '南京金陵医疗器械有限公司',
    '金陵医疗',
    '企业',
    '医疗器械',
    '025-84562318',
    '南京',
    '官网咨询',
    '普通',
  ],
  [
    '武汉长江智能制造研究院',
    '长江智造',
    '事业单位',
    '智能制造',
    '027-87891245',
    '武汉',
    '政府项目',
    '重点',
  ],
  [
    '西安秦创原科技服务有限公司',
    '秦创原服务',
    '企业',
    '科技服务',
    '029-88451267',
    '西安',
    '合作伙伴',
    '潜在',
  ],
  [
    '重庆山城供应链管理有限公司',
    '山城供应链',
    '企业',
    '供应链管理',
    '023-63851290',
    '重庆',
    '客户转介绍',
    '普通',
  ],
  [
    '苏州工业园区城市运营有限公司',
    '园区运营',
    '企业',
    '城市运营',
    '0512-66681234',
    '苏州',
    '行业交流',
    '重点',
  ],
  [
    '天津滨海新区公共资源交易中心',
    '滨海交易中心',
    '政府',
    '公共服务',
    '022-65381276',
    '天津',
    '政府项目',
    '重点',
  ],
  [
    '青岛海信数字产业发展有限公司',
    '海信数字',
    '企业',
    '数字产业',
    '0532-85761288',
    '青岛',
    '官网咨询',
    '普通',
  ],
  [
    '厦门鹭岛软件技术有限公司',
    '鹭岛软件',
    '企业',
    '软件服务',
    '0592-5321680',
    '厦门',
    '市场活动',
    '普通',
  ],
  [
    '郑州中原能源投资集团有限公司',
    '中原能源',
    '企业',
    '能源投资',
    '0371-67981201',
    '郑州',
    '合作伙伴',
    '重点',
  ],
  [
    '长沙湘江新区建设投资有限公司',
    '湘江建投',
    '企业',
    '基础设施',
    '0731-88981234',
    '长沙',
    '政府项目',
    '重点',
  ],
  [
    '济南泉城金融控股集团有限公司',
    '泉城金控',
    '企业',
    '金融服务',
    '0531-82981256',
    '济南',
    '客户转介绍',
    '普通',
  ],
  [
    '福州海峡信息技术有限公司',
    '海峡信息',
    '企业',
    '信息技术',
    '0591-87861209',
    '福州',
    '官网咨询',
    '潜在',
  ],
  [
    '合肥科大成果转化中心',
    '科大转化中心',
    '事业单位',
    '科技成果转化',
    '0551-63681218',
    '合肥',
    '行业交流',
    '重点',
  ],
  [
    '昆明云岭生态农业集团有限公司',
    '云岭农业',
    '企业',
    '生态农业',
    '0871-63181245',
    '昆明',
    '展会获客',
    '普通',
  ],
  [
    '沈阳盛京装备制造有限公司',
    '盛京装备',
    '企业',
    '装备制造',
    '024-24861234',
    '沈阳',
    '合作伙伴',
    '普通',
  ],
  [
    '哈尔滨冰城数据服务有限公司',
    '冰城数据',
    '企业',
    '数据服务',
    '0451-87981260',
    '哈尔滨',
    '官网咨询',
    '潜在',
  ],
  [
    '石家庄华北医药物流有限公司',
    '华北医药物流',
    '企业',
    '医药物流',
    '0311-85681237',
    '石家庄',
    '客户转介绍',
    '普通',
  ],
  [
    '南昌赣江新区产业投资集团',
    '赣江产投',
    '企业',
    '产业投资',
    '0791-83861245',
    '南昌',
    '政府项目',
    '重点',
  ],
  [
    '贵阳黔云大数据产业发展有限公司',
    '黔云数据',
    '企业',
    '大数据',
    '0851-86881209',
    '贵阳',
    '行业交流',
    '重点',
  ],
  [
    '太原晋阳企业服务中心',
    '晋阳企服',
    '事业单位',
    '企业服务',
    '0351-73381256',
    '太原',
    '市场活动',
    '普通',
  ],
  [
    '兰州黄河水务建设有限公司',
    '黄河水务',
    '企业',
    '水务环保',
    '0931-88261234',
    '兰州',
    '政府项目',
    '重点',
  ],
  [
    '海口椰城会展服务有限公司',
    '椰城会展',
    '企业',
    '会展服务',
    '0898-68581267',
    '海口',
    '展会获客',
    '普通',
  ],
  [
    '宁波甬江港口物流有限公司',
    '甬江港口',
    '企业',
    '港口物流',
    '0574-87681245',
    '宁波',
    '合作伙伴',
    '重点',
  ],
  [
    '无锡太湖新城科创发展有限公司',
    '太湖科创',
    '企业',
    '科技园区',
    '0510-81881209',
    '无锡',
    '官网咨询',
    '潜在',
  ],
  [
    '东莞华南电子商务有限公司',
    '华南电商',
    '企业',
    '电子商务',
    '0769-22881234',
    '东莞',
    '客户转介绍',
    '普通',
  ],
  [
    '佛山岭南家居制造有限公司',
    '岭南家居',
    '企业',
    '家居制造',
    '0757-83381256',
    '佛山',
    '行业交流',
    '重点',
  ],
  [
    '珠海横琴金融科技有限公司',
    '横琴金科',
    '企业',
    '金融科技',
    '0756-88981267',
    '珠海',
    '官网咨询',
    '重点',
  ],
  [
    '温州瓯越商贸集团有限公司',
    '瓯越商贸',
    '企业',
    '商贸流通',
    '0577-88981245',
    '温州',
    '客户转介绍',
    '普通',
  ],
  [
    '徐州淮海数据产业园有限公司',
    '淮海数据园',
    '企业',
    '产业园区',
    '0516-83881209',
    '徐州',
    '政府项目',
    '潜在',
  ],
  [
    '常州龙城新能源科技有限公司',
    '龙城新能源',
    '企业',
    '新能源',
    '0519-86881234',
    '常州',
    '展会获客',
    '重点',
  ],
  [
    '烟台蓬莱葡萄酒集团有限公司',
    '蓬莱酒业',
    '企业',
    '食品饮料',
    '0535-66881256',
    '烟台',
    '合作伙伴',
    '普通',
  ],
  [
    '唐山曹妃甸港口发展有限公司',
    '曹妃甸港',
    '企业',
    '港口服务',
    '0315-88281267',
    '唐山',
    '政府项目',
    '重点',
  ],
  [
    '洛阳中科先进材料研究院',
    '中科材料院',
    '事业单位',
    '新材料',
    '0379-65181245',
    '洛阳',
    '行业交流',
    '重点',
  ],
  [
    '呼和浩特草原智算科技有限公司',
    '草原智算',
    '企业',
    '云计算',
    '0471-63581209',
    '呼和浩特',
    '官网咨询',
    '潜在',
  ],
  [
    '乌鲁木齐天山商贸服务有限公司',
    '天山商贸',
    '企业',
    '商贸服务',
    '0991-46881234',
    '乌鲁木齐',
    '客户转介绍',
    '普通',
  ],
  [
    '银川塞上智慧农业有限公司',
    '塞上农业',
    '企业',
    '智慧农业',
    '0951-68981256',
    '银川',
    '展会获客',
    '重点',
  ],
  [
    '西宁青唐生态环境有限公司',
    '青唐环保',
    '企业',
    '生态环保',
    '0971-62681267',
    '西宁',
    '政府项目',
    '普通',
  ],
  [
    '拉萨雪域文化数字传播中心',
    '雪域文化',
    '事业单位',
    '文化传播',
    '0891-63281245',
    '拉萨',
    '行业交流',
    '重点',
  ],
  [
    '丽江玉龙旅游投资有限公司',
    '玉龙旅投',
    '企业',
    '旅游投资',
    '0888-51281209',
    '丽江',
    '合作伙伴',
    '普通',
  ],
  [
    '扬州运河文创产业集团',
    '运河文创',
    '企业',
    '文化创意',
    '0514-87881234',
    '扬州',
    '市场活动',
    '潜在',
  ],
  [
    '绍兴越城城市更新有限公司',
    '越城更新',
    '企业',
    '城市更新',
    '0575-85181256',
    '绍兴',
    '政府项目',
    '重点',
  ],
  [
    '保定白洋淀生态建设有限公司',
    '白洋淀生态',
    '企业',
    '生态建设',
    '0312-50681267',
    '保定',
    '官网咨询',
    '普通',
  ],
  [
    '大连星海信息咨询有限公司',
    '星海咨询',
    '企业',
    '咨询服务',
    '0411-82581245',
    '大连',
    '客户转介绍',
    '潜在',
  ],
  [
    '吉林北方教育科技集团',
    '北方教育',
    '企业',
    '教育科技',
    '0431-85681209',
    '长春',
    '展会获客',
    '普通',
  ],
];

const contactNames = [
  '刘思远',
  '沈嘉怡',
  '陈宇航',
  '周婉清',
  '何俊杰',
  '赵子涵',
  '孙明远',
  '林若溪',
  '高博文',
  '唐婉',
];
const positions = [
  '项目总监',
  '信息化平台主管',
  '运营负责人',
  '综合管理部经理',
  '采购经理',
  '数字化平台主管',
  '招商主管',
  '行政总监',
  '技术负责人',
  '财务负责人',
];
const followTypes = [
  '电话沟通',
  '现场拜访',
  '微信沟通',
  '邮件沟通',
  '在线会议',
];
const stages = ['初步接触', '需求确认', '方案报价', '商务谈判', '决策中'];
const opportunityNames = [
  '档案数字化平台建设',
  '客户管理系统升级',
  '数据治理与智能检索项目',
  '年度信息化服务采购',
  '移动办公协同平台',
  '知识库建设项目',
  '系统运维服务续约',
  '智慧运营可视化项目',
];

const demoUsers = [
  [
    'demo-sales-01',
    'chenxi',
    '陈曦',
    '13800000101',
    'chenxi@huadang.com',
    'sales',
    'p3',
    'u2',
    'sales',
  ],
  [
    'demo-sales-02',
    'zhouchen',
    '周辰',
    '13800000102',
    'zhouchen@huadang.com',
    'sales',
    'p3',
    'u2',
    'sales',
  ],
  [
    'demo-sales-03',
    'linna',
    '林娜',
    '13800000103',
    'linna@huadang.com',
    'sales',
    'p3',
    'u2',
    'sales',
  ],
  [
    'demo-sales-04',
    'gaoyang',
    '高阳',
    '13800000104',
    'gaoyang@huadang.com',
    'sales',
    'p3',
    'u2',
    'sales',
  ],
  [
    'demo-delivery-01',
    'xuyifan',
    '徐逸凡',
    '13800000105',
    'xuyifan@huadang.com',
    'delivery',
    'p4',
    'u1',
    'project-manager',
  ],
  [
    'demo-delivery-02',
    'hewenbo',
    '何文博',
    '13800000106',
    'hewenbo@huadang.com',
    'delivery',
    'p4',
    'u1',
    'project-manager',
  ],
  [
    'demo-finance-01',
    'lujing',
    '陆静',
    '13800000107',
    'lujing@huadang.com',
    'finance',
    'p5',
    'u1',
    'finance',
  ],
  [
    'demo-finance-02',
    'tangrui',
    '唐睿',
    '13800000108',
    'tangrui@huadang.com',
    'finance',
    'p5',
    'u1',
    'finance',
  ],
] as const;

export async function ensureDemoUsers() {
  for (const [
    id,
    username,
    realName,
    phone,
    email,
    deptId,
    positionId,
    leaderId,
    roleCode,
  ] of demoUsers) {
    await query(
      `INSERT INTO sys_user(id,username,password,real_name,phone,email,dept_id,position_id,leader_id,status,locked,must_change_password,remark) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,1,false,false,$10) ON CONFLICT (id) DO NOTHING`,
      [
        id,
        username,
        hashPassword('ChangeMe!2026'),
        realName,
        phone,
        email,
        deptId,
        positionId,
        leaderId,
        `演示账号：${realName}，用于模拟真实业务协作。`,
      ],
    );
    await query(
      `INSERT INTO sys_user_role(user_id,role_id) SELECT $1,id FROM sys_role WHERE code=$2 ON CONFLICT DO NOTHING`,
      [id, roleCode],
    );
  }
}

export async function ensureBusinessSeedData() {
  await ensureDemoUsers();
  for (let i = 0; i < Math.min(customerProfiles.length, 10); i++) {
    const [name, shortName, type, industry, phone, region, source, level] =
      customerProfiles[i]!;
    await query(
      `INSERT INTO crm_customer(id,name,short_name,type,industry,phone,region,source,level,remark) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT (id) DO NOTHING`,
      [
        `crm-customer-${String(i + 1).padStart(3, '0')}`,
        name,
        shortName,
        type,
        industry,
        phone,
        region,
        source,
        level,
        `${name}的客户档案与项目合作信息。`,
      ],
    );
  }

  // 演示客户的负责人只从真实的 sales 角色用户中分配，负责人值保存用户主键。
  const demoSalesIds = [
    'demo-sales-01',
    'demo-sales-02',
    'demo-sales-03',
    'demo-sales-04',
    'u3',
  ];
  for (let i = 0; i < 10; i++) {
    const customerId = `crm-customer-${String(i + 1).padStart(3, '0')}`;
    await query(
      `UPDATE crm_customer SET owner_id=$1 WHERE id=$2 AND (owner_id IS NULL OR owner_id IN ('demo-delivery-01','demo-delivery-02'))`,
      [demoSalesIds[i % demoSalesIds.length], customerId],
    );
  }
  for (let i = 0; i < 10; i++) {
    const customerId = `crm-customer-${String((i % 50) + 1).padStart(3, '0')}`;
    const name = contactNames[i % contactNames.length]!;
    await query(
      `INSERT INTO crm_contact(id,customer_id,name,gender,position,contact_type,contact_business,mobile,email,is_primary,remark) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT (id) DO UPDATE SET contact_business=CASE WHEN COALESCE(crm_contact.contact_business,'')='' THEN EXCLUDED.contact_business ELSE crm_contact.contact_business END`,
      [
        `crm-contact-${String(i + 1).padStart(3, '0')}`,
        customerId,
        name,
        i % 2 ? '女' : '男',
        positions[i % positions.length],
        i % 3 ? '业务联系人' : '关键决策人',
        [
          '文档业务',
          '组工业务、合同审批',
          '培训业务',
          '财务结算',
          '技术对接、文档业务',
        ][i % 5],
        `13${String(810_000_000 + i * 137).slice(-9)}`,
        `contact${i + 1}@example.com`,
        true,
        `${name}负责项目沟通、需求确认与商务协同。`,
      ],
    );
  }

  for (let i = 0; i < 10; i++) {
    const customerId = `crm-customer-${String((i % 50) + 1).padStart(3, '0')}`;
    const contactId = `crm-contact-${String((i % 50) + 1).padStart(3, '0')}`;
    const stage = stages[i % stages.length]!;
    const opportunityId = `crm-opportunity-${String(i + 1).padStart(3, '0')}`;
    await query(
      `INSERT INTO crm_opportunity(id,customer_id,primary_contact_id,owner_id,name,source,stage,status,amount,probability,expected_close_date,next_plan,next_follow_time,risk_level,description) SELECT $1,$2,$3,c.owner_id,$4,$5,$6,'进行中',$7,$8,$9,$10,$11,$12,$13 FROM crm_customer c WHERE c.id=$2 ON CONFLICT (id) DO NOTHING`,
      [
        opportunityId,
        customerId,
        contactId,
        `${opportunityNames[i % opportunityNames.length]}（${i + 1}期）`,
        i % 2 ? '官网咨询' : '客户转介绍',
        stage,
        180_000 + (i % 9) * 85_000,
        [10, 25, 45, 65, 80][i % 5],
        `2026-${String((i % 6) + 7).padStart(2, '0')}-15`,
        '安排方案评审并确认采购流程',
        new Date(Date.UTC(2026, 6 + (i % 6), 18, 2, 0)),
        i % 7 === 0 ? '较高' : '正常',
        '围绕客户现有业务流程进行系统建设与服务报价。',
      ],
    );
    await query(
      `INSERT INTO crm_opportunity_stage_history(id,opportunity_id,from_stage,to_stage,note) VALUES($1,$2,'',$3,$4) ON CONFLICT (id) DO NOTHING`,
      [
        `crm-opportunity-history-${String(i + 1).padStart(3, '0')}`,
        opportunityId,
        stage,
        '初始化演示数据',
      ],
    );
  }

  for (let i = 0; i < 10; i++) {
    const customerId = `crm-customer-${String((i % 50) + 1).padStart(3, '0')}`;
    const contactId = `crm-contact-${String((i % 50) + 1).padStart(3, '0')}`;
    const opportunityId = `crm-opportunity-${String((i % 50) + 1).padStart(3, '0')}`;
    const followTime = new Date(
      Date.UTC(2026, 5 + (i % 3), 3 + (i % 20), 2, 0),
    );
    await query(
      `INSERT INTO crm_follow_up(id,customer_id,contact_id,opportunity_id,owner_id,follow_up_time,follow_up_type,subject,content,result,intention_level,next_plan,next_follow_time,status,remark) SELECT $1,$2,$3,$4,c.owner_id,$5,$6,$7,$8,$9,$10,$11,$12,'待跟进',$13 FROM crm_customer c WHERE c.id=$2 ON CONFLICT (id) DO NOTHING`,
      [
        `crm-follow-up-${String(i + 1).padStart(3, '0')}`,
        customerId,
        contactId,
        opportunityId,
        followTime,
        followTypes[i % followTypes.length],
        `${i % 3 === 0 ? '首次需求沟通' : i % 3 === 1 ? '方案反馈跟进' : '商务推进沟通'}-${i + 1}`,
        `与客户${i % 2 ? '线上' : '现场'}沟通，确认${i % 2 ? '预算范围及上线计划' : '业务需求与关键审批节点'}，客户反馈积极。`,
        i % 4 === 0 ? '已获取需求清单' : '客户认可初步方案',
        i % 5 === 0 ? '高' : i % 3 === 0 ? '中' : '低',
        '整理会议纪要，补充报价明细并约定下一次评审',
        new Date(followTime.getTime() + 7 * 24 * 3600 * 1000),
        `演示跟进记录：第${i + 1}次客户沟通。`,
      ],
    );
  }

  const employeeNames = [
    '李晨',
    '王芳',
    '赵敏',
    '刘洋',
    '周宁',
    '陈静',
    '杨帆',
    '黄欣',
    '孙磊',
    '吴倩',
    '郑凯',
    '何琳',
    '高阳',
    '林娜',
    '张伟',
    '周辰',
    '陈曦',
    '马超',
    '徐颖',
    '郭鹏',
    '沈悦',
    '彭博',
    '蒋婷',
    '韩旭',
    '罗倩',
    '谢辉',
    '唐婉',
    '魏杰',
    '宋佳',
    '许晨',
    '冯雪',
    '邓凯',
    '梁爽',
    '潘宇',
    '朱琳',
    '董浩',
    '苏妍',
    '袁野',
    '胡敏',
    '程远',
    '谭静',
    '陆阳',
    '白雪',
    '邱明',
    '顾楠',
    '石磊',
    '秦悦',
    '范伟',
    '杜娟',
    '林浩',
  ];
  const employeeDepartments = ['销售中心', '交付中心', '财务部', '档案事业部'];
  const employeePositions = ['客户经理', '项目经理', '财务专员', '档案专员'];
  for (let i = 0; i < 10; i++) {
    const n = String(i + 1).padStart(3, '0');
    const month = String((i % 9) + 1).padStart(2, '0');
    const day = String((i % 28) + 1).padStart(2, '0');
    await query(
      `INSERT INTO hr_employee(id,employee_no,name,gender,birthday,mobile,email,id_card_no,bank_name,bank_account,emergency_contact,emergency_mobile,dept_name,position,entry_date,status,labor_contract_start,labor_contract_end,labor_contract_no,remark) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20) ON CONFLICT(id) DO NOTHING`,
      [
        `hr-demo-${n}`,
        `EMP${String(i + 1).padStart(4, '0')}`,
        employeeNames[i],
        i % 2 ? '女' : '男',
        `1990-${month}-${day}`,
        `138${String(10_000_000 + i * 17_321).slice(-8)}`,
        `employee${i + 1}@huadang.example.com`,
        `110101199${String(100_000 + i).padStart(6, '0')}${String((i % 9) + 1)}`,
        '中国建设银行',
        `622200000000${String(i + 1).padStart(4, '0')}`,
        i % 2 ? '王芳' : '李强',
        `139${String(20_000_000 + i * 27_113).slice(-8)}`,
        employeeDepartments[i % 4],
        employeePositions[i % 4],
        `202${i % 4}-${month}-${day}`,
        i % 12 === 0 ? '试用期' : '在职',
        `202${i % 4}-${month}-01`,
        `202${(i % 4) + 4}-${month}-01`,
        `LC-${String(i + 1).padStart(4, '0')}`,
        '人事行政测试档案，用于联调验证。',
      ],
    );
  }
  const ownerIds = [
    'demo-sales-01',
    'demo-sales-02',
    'demo-sales-03',
    'demo-sales-04',
    'u3',
  ];
  for (let i = 0; i < 10; i++) {
    const n = String(i + 1).padStart(3, '0');
    const customerId = `crm-customer-${n}`;
    const contractId = `crm-contract-demo-${n}`;
    const invoiceId = `crm-invoice-demo-${n}`;
    const amount = 120_000 + i * 8500;
    const invoiceAmount = Math.round(amount * 0.4 * 100) / 100;
    const paymentAmount = Math.round(amount * 0.25 * 100) / 100;
    const month = String((i % 9) + 1).padStart(2, '0');
    const ownerId = ownerIds[i % ownerIds.length];
    const items = JSON.stringify({
      items: [
        {
          name: i % 2 ? '档案整理与数字化服务' : '业务系统建设服务',
          quantity: 1,
          unitPrice: amount,
          amount,
        },
      ],
      paymentPlans: [
        { name: '首期款', ratio: 25, amount: paymentAmount },
        { name: '阶段款', ratio: 40, amount: amount * 0.4 },
        { name: '尾款', ratio: 35, amount: amount * 0.35 },
      ],
      attachments: [],
    });
    await query(
      `INSERT INTO crm_contract(id,contract_no,contract_name,customer_id,contact_name,project_name,project_no,archive_no,archived_at,signed_at,amount,owner_id,project_type,payment_method,quality_deposit,project_period,status,remark,items) SELECT $1,$2,$3,$4,coalesce(ct.name,''),$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18::jsonb FROM crm_customer c LEFT JOIN crm_contact ct ON ct.customer_id=c.id AND ct.is_primary=true WHERE c.id=$4 ON CONFLICT(id) DO NOTHING`,
      [
        contractId,
        `HT-2026-${n}`,
        `${i % 2 ? '档案整理服务' : '业务系统建设'}合同-${n}`,
        customerId,
        `${i % 2 ? '档案数字化项目' : '客户管理系统项目'}-${n}`,
        `PRJ-2026-${n}`,
        `ARC-2026-${n}`,
        `2026-${month}-28`,
        `2026-${month}-15`,
        amount,
        ownerId,
        i % 2 ? '文档' : '组工',
        '银行转账',
        Math.round(amount * 0.05 * 100) / 100,
        i % 2 ? '6个月' : '12个月',
        i % 10 === 0 ? '已完成' : '执行中',
        '关联演示客户的正式合同测试数据。',
        items,
      ],
    );
    await query(
      `INSERT INTO crm_contract_invoice(id,contract_id,customer_id,invoice_amount,invoice_type,invoice_no,issued_at,status,remark,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,'有效',$8,$9) ON CONFLICT(id) DO NOTHING`,
      [
        invoiceId,
        contractId,
        customerId,
        invoiceAmount,
        i % 2 ? '增值税专用发票' : '增值税普通发票',
        `FP-2026-${n}`,
        `2026-${month}-20`,
        '与合同对应的首期开票记录。',
        ownerId,
      ],
    );
    await query(
      `INSERT INTO crm_contract_payment(id,contract_id,customer_id,payment_amount,payment_date,payment_method,payment_account,receipt_no,status,invoice_id,remark,created_by) VALUES($1,$2,$3,$4,$5,'银行转账',$6,$7,'已到账',$8,$9,$10) ON CONFLICT(id) DO NOTHING`,
      [
        `crm-payment-demo-${n}`,
        contractId,
        customerId,
        paymentAmount,
        `2026-${month}-18`,
        i % 2 ? '招商银行北京分行' : '中国工商银行北京分行',
        `SK-2026-${n}`,
        invoiceId,
        '合同首期回款，已与发票关联。',
        ownerId,
      ],
    );
  }
}
