// Static menu metadata used by the database bootstrap. Business entities are database-backed.
export const systemMenus: any[] = [
  {
    id: 'm-customer',
    pid: null,
    name: 'Customer',
    title: '\u5BA2\u6237\u4E2D\u5FC3',
    type: 'catalog',
    path: '/operations/customer',
    component: '',
    authCode: 'customer',
    icon: 'carbon:customer-service',
    status: 1,
    sort: 2,
  },
  {
    id: 'm-contract',
    pid: null,
    name: 'Contract',
    title: '\u5408\u540C\u4E2D\u5FC3',
    type: 'catalog',
    path: '/operations/contract',
    component: '',
    authCode: 'contract',
    icon: 'carbon:document',
    status: 1,
    sort: 3,
  },
  {
    id: 'm-analytics-center',
    pid: null,
    name: 'Analytics',
    title: '统计分析',
    type: 'catalog',
    path: '/operations/analytics',
    component: '',
    authCode: 'analytics',
    icon: 'carbon:chart-line',
    status: 1,
    sort: 4,
  },
  {
    id: 'm-sales-analytics',
    pid: 'm-analytics-center',
    name: 'SalesAnalytics',
    title: '销售分析',
    type: 'menu',
    path: 'sales',
    component: 'operations/sales-analytics',
    authCode: 'analytics:sales:view',
    icon: 'carbon:chart-line-data',
    status: 1,
    sort: 1,
  },
  {
    id: 'm-system',
    pid: null,
    name: 'System',
    title: '\u7CFB\u7EDF\u7BA1\u7406',
    type: 'catalog',
    path: '/operations/system',
    component: '',
    authCode: 'system',
    icon: 'carbon:settings',
    status: 1,
    sort: 8,
  },
  {
    id: 'm-users',
    pid: 'm-system',
    name: 'Users',
    title: '\u7528\u6237\u7BA1\u7406',
    type: 'menu',
    path: 'users',
    component: 'system/user/index',
    authCode: 'system:user:view',
    icon: 'carbon:user-multiple',
    status: 1,
    sort: 1,
  },
  {
    id: 'm-user-create',
    pid: 'm-users',
    name: 'UserCreate',
    title: '\u65B0\u589E\u7528\u6237',
    type: 'button',
    path: '',
    component: '',
    authCode: 'system:user:create',
    icon: '',
    status: 1,
    sort: 1,
  },
  {
    id: 'm-roles',
    pid: 'm-system',
    name: 'Roles',
    title: '\u89D2\u8272\u7BA1\u7406',
    type: 'menu',
    path: 'roles',
    component: 'system/roles/index',
    authCode: 'system:role:view',
    icon: 'carbon:user-role',
    status: 1,
    sort: 2,
  },
  {
    id: 'm-org',
    pid: 'm-system',
    name: 'Organization',
    title: '\u90E8\u95E8\u4E0E\u5C97\u4F4D',
    type: 'menu',
    path: 'organization',
    component: 'system/organization/index',
    authCode: 'system:org:view',
    icon: 'carbon:tree-view',
    status: 1,
    sort: 3,
  },
  {
    id: 'm-permissions',
    pid: 'm-system',
    name: 'Permissions',
    title: '\u83DC\u5355\u6743\u9650',
    type: 'menu',
    path: 'permissions',
    component: 'system/menu/index',
    authCode: 'system:menu:view',
    icon: 'carbon:security',
    status: 1,
    sort: 4,
  },
];
export const auditLogs: any[] = [];

export const systemSettings: any = {
  systemName: '华档致远',
  companyName: '北京华档致远科技有限公司',
  timezone: 'Asia/Shanghai',
  defaultPageSize: 20,
  maxUploadSizeMb: 20,
  logMode: 'important',
  logRetentionDays: 365,
  detailModeHours: 24,
  passwordMinLength: 8,
  passwordMaxLength: 32,
  passwordRequireLettersAndNumbers: true,
  maxLoginFailures: 5,
  lockMinutes: 30,
  crossSalesVisibility: 'full',
};

export function ensureSystemMenuEntries() {
  let changed = false;
  const entries = [
    [
      'm-customer',
      null,
      'Customer',
      '客户中心',
      'catalog',
      '/operations/customer',
      '',
      'customer',
      'carbon:customer-service',
      2,
    ],
    [
      'm-contract',
      null,
      'Contract',
      '合同中心',
      'catalog',
      '/operations/contract',
      '',
      'contract',
      'carbon:document',
      3,
    ],
    [
      'm-hr',
      null,
      'Hr',
      '人事行政',
      'catalog',
      '/operations/hr',
      '',
      'hr',
      'carbon:identification',
      2,
    ],
    [
      'm-employees',
      'm-hr',
      'Employees',
      '员工档案',
      'menu',
      'employees',
      'operations/hr-employees',
      'hr:employee:view',
      'carbon:chevron-right',
      1,
    ],
    [
      'm-employee-create', 'm-employees', 'EmployeeCreate', '新增员工', 'button', '', '', 'hr:employee:create', '', 1,
    ],
    [
      'm-employee-edit', 'm-employees', 'EmployeeEdit', '编辑员工', 'button', '', '', 'hr:employee:update', '', 2,
    ],
    [
      'm-employee-delete', 'm-employees', 'EmployeeDelete', '删除员工', 'button', '', '', 'hr:employee:delete', '', 3,
    ],
    [
      'm-employee-upload', 'm-employees', 'EmployeeUpload', '上传员工附件', 'button', '', '', 'hr:employee:upload', '', 4,
    ],
    [
      'm-analytics-center',
      null,
      'Analytics',
      '统计分析',
      'catalog',
      '/operations/analytics',
      '',
      'analytics',
      'carbon:chart-line',
      4,
    ],
    [
      'm-sales-analytics',
      'm-analytics-center',
      'SalesAnalytics',
      '销售分析',
      'menu',
      'sales',
      'operations/sales-analytics',
      'analytics:sales:view',
      'carbon:chart-line-data',
      1,
    ],
    [
      'm-system',
      null,
      'System',
      '系统管理',
      'catalog',
      '/operations/system',
      '',
      'system',
      'carbon:settings',
      8,
    ],
    [
      'm-users',
      'm-system',
      'Users',
      '用户管理',
      'menu',
      'users',
      'system/user/index',
      'system:user:view',
      'carbon:user-multiple',
      1,
    ],
    [
      'm-user-create', 'm-users', 'UserCreate', '新增用户', 'button', '', '', 'system:user:create', '', 1,
    ],
    [
      'm-user-edit', 'm-users', 'UserEdit', '编辑用户', 'button', '', '', 'system:user:update', '', 2,
    ],
    [
      'm-user-delete', 'm-users', 'UserDelete', '停用用户', 'button', '', '', 'system:user:delete', '', 3,
    ],
    [
      'm-user-reset-password', 'm-users', 'UserResetPassword', '重置密码', 'button', '', '', 'system:user:reset-password', '', 4,
    ],
    [
      'm-roles',
      'm-system',
      'Roles',
      '角色管理',
      'menu',
      'roles',
      'system/roles/index',
      'system:role:view',
      'carbon:user-role',
      2,
    ],
    [
      'm-org',
      'm-system',
      'Organization',
      '部门与岗位',
      'menu',
      'organization',
      'system/organization/index',
      'system:org:view',
      'carbon:tree-view',
      3,
    ],
    [
      'm-permissions',
      'm-system',
      'Permissions',
      '菜单权限',
      'menu',
      'permissions',
      'system/menu/index',
      'system:menu:view',
      'carbon:security',
      4,
    ],
    [
      'm-settings',
      'm-system',
      'Settings',
      '系统设置',
      'menu',
      'settings',
      'system/settings/index',
      'system:settings:view',
      'carbon:settings-adjust',
      5,
    ],
    [
      'm-audit-logs',
      'm-system',
      'AuditLogs',
      '操作日志',
      'menu',
      'audit-logs',
      'system/audit-logs/index',
      'system:audit:view',
      'carbon:activity',
      6,
    ],
    [
      'm-recycle-bin',
      'm-system',
      'RecycleBin',
      '回收站',
      'menu',
      'recycle-bin',
      'system/recycle-bin/index',
      'system:recycle:view',
      'carbon:trash-can',
      7,
    ],
  ];
  const businessPermissions = [
    [
      'm-customer-invoice-profile', 'm-customer', 'CustomerInvoiceProfile', '开票信息管理', 'menu', 'invoice-profiles', 'operations/customer-invoice-profiles', 'customer:invoice-profile:list:view', 'carbon:document', 2,
    ],
    [
      'm-customer-invoice-profile-create', 'm-customer-invoice-profile', 'CustomerInvoiceProfileCreate', '新增开票信息', 'button', '', '', 'customer:invoice-profile:create', '', 1,
    ],
    [
      'm-customer-list',
      'm-customer',
      'CustomerList',
      '客户列表',
      'menu',
      'list',
      'operations/customer',
      'customer:list:view',
      'carbon:list',
      1,
    ],
    [
      'm-customer-create',
      'm-customer-list',
      'CustomerCreate',
      '新增客户',
      'button',
      '',
      '',
      'customer:create',
      '',
      1,
    ],
    [
      'm-customer-view',
      'm-customer-list',
      'CustomerView',
      '查看客户',
      'button',
      '',
      '',
      'customer:view',
      '',
      2,
    ],
    [
      'm-customer-edit',
      'm-customer-list',
      'CustomerEdit',
      '编辑客户',
      'button',
      '',
      '',
      'customer:update',
      '',
      3,
    ],
    [
      'm-customer-delete',
      'm-customer-list',
      'CustomerDelete',
      '删除客户',
      'button',
      '',
      '',
      'customer:delete',
      '',
      4,
    ],
    [
      'm-customer-import',
      'm-customer-list',
      'CustomerImport',
      '导入客户',
      'button',
      '',
      '',
      'customer:import',
      '',
      5,
    ],
    [
      'm-customer-export',
      'm-customer-list',
      'CustomerExport',
      '导出客户',
      'button',
      '',
      '',
      'customer:export',
      '',
      6,
    ],
    [
      'm-customer-transfer',
      'm-customer',
      'CustomerTransfer',
      '客户转移',
      'menu',
      'transfer',
      'operations/customer-transfer',
      'customer:transfer:view',
      'carbon:share',
      2,
    ],
    [
      'm-customer-transfer-create',
      'm-customer-transfer',
      'CustomerTransferCreate',
      '发起转移',
      'button',
      '',
      '',
      'customer:transfer:create',
      '',
      1,
    ],
    [
      'm-customer-transfer-reverse',
      'm-customer-transfer',
      'CustomerTransferReverse',
      '撤销转移',
      'button',
      '',
      '',
      'customer:transfer:reverse',
      '',
      2,
    ],
    [
      'm-contact',
      'm-customer',
      'Contact',
      '联系人',
      'menu',
      'contacts',
      'operations/contacts',
      'contact:list:view',
      'carbon:group',
      3,
    ],
    [
      'm-contact-create',
      'm-contact',
      'ContactCreate',
      '新增联系人',
      'button',
      '',
      '',
      'contact:create',
      '',
      1,
    ],
    [
      'm-contact-view',
      'm-contact',
      'ContactView',
      '查看联系人',
      'button',
      '',
      '',
      'contact:view',
      '',
      2,
    ],
    [
      'm-contact-edit',
      'm-contact',
      'ContactEdit',
      '编辑联系人',
      'button',
      '',
      '',
      'contact:update',
      '',
      3,
    ],
    [
      'm-contact-delete',
      'm-contact',
      'ContactDelete',
      '删除联系人',
      'button',
      '',
      '',
      'contact:delete',
      '',
      4,
    ],
    [
      'm-follow-up',
      'm-customer',
      'FollowUp',
      '跟进记录',
      'menu',
      'follow-ups',
      'operations/follow-ups',
      'followup:list:view',
      'carbon:task',
      4,
    ],
    [
      'm-follow-up-create',
      'm-follow-up',
      'FollowUpCreate',
      '新增跟进',
      'button',
      '',
      '',
      'followup:create',
      '',
      1,
    ],
    [
      'm-follow-up-edit',
      'm-follow-up',
      'FollowUpEdit',
      '编辑跟进',
      'button',
      '',
      '',
      'followup:update',
      '',
      2,
    ],
    [
      'm-follow-up-delete',
      'm-follow-up',
      'FollowUpDelete',
      '删除跟进',
      'button',
      '',
      '',
      'followup:delete',
      '',
      3,
    ],
    [
      'm-opportunity',
      'm-customer',
      'Opportunity',
      '销售机会',
      'menu',
      'opportunities',
      'operations/opportunities',
      'opportunity:list:view',
      'carbon:chart-line',
      5,
    ],
    [
      'm-opportunity-create',
      'm-opportunity',
      'OpportunityCreate',
      '新增机会',
      'button',
      '',
      '',
      'opportunity:create',
      '',
      1,
    ],
    [
      'm-opportunity-view',
      'm-opportunity',
      'OpportunityView',
      '查看机会',
      'button',
      '',
      '',
      'opportunity:view',
      '',
      2,
    ],
    [
      'm-opportunity-edit',
      'm-opportunity',
      'OpportunityEdit',
      '编辑机会',
      'button',
      '',
      '',
      'opportunity:update',
      '',
      3,
    ],
    [
      'm-opportunity-delete',
      'm-opportunity',
      'OpportunityDelete',
      '删除机会',
      'button',
      '',
      '',
      'opportunity:delete',
      '',
      4,
    ],
    [
      'm-contract-list',
      'm-contract',
      'ContractList',
      '合同列表',
      'menu',
      'list',
      'operations/contract-list',
      'contract:list:view',
      'carbon:list',
      1,
    ],
    [
      'm-contract-create',
      'm-contract-list',
      'ContractCreate',
      '新增合同',
      'button',
      '',
      '',
      'contract:create',
      '',
      1,
    ],
    [
      'm-contract-view',
      'm-contract-list',
      'ContractView',
      '查看合同',
      'button',
      '',
      '',
      'contract:view',
      '',
      2,
    ],
    [
      'm-contract-edit',
      'm-contract-list',
      'ContractEdit',
      '编辑合同',
      'button',
      '',
      '',
      'contract:update',
      '',
      3,
    ],
    [
      'm-contract-delete',
      'm-contract-list',
      'ContractDelete',
      '删除合同',
      'button',
      '',
      '',
      'contract:delete',
      '',
      4,
    ],
    [
      'm-invoice',
      'm-contract',
      'Invoice',
      '发票管理',
      'menu',
      'invoices',
      'operations/contract-invoices',
      'invoice:list:view',
      'carbon:receipt',
      2,
    ],
    [
      'm-invoice-create',
      'm-invoice',
      'InvoiceCreate',
      '录入发票',
      'button',
      '',
      '',
      'invoice:create',
      '',
      1,
    ],
    [
      'm-invoice-view',
      'm-invoice',
      'InvoiceView',
      '查看发票',
      'button',
      '',
      '',
      'invoice:view',
      '',
      2,
    ],
    [
      'm-invoice-void',
      'm-invoice',
      'InvoiceVoid',
      '发票作废',
      'button',
      '',
      '',
      'invoice:void',
      '',
      3,
    ],
    [
      'm-payment',
      'm-contract',
      'Payment',
      '回款管理',
      'menu',
      'payments',
      'operations/contract-payments',
      'payment:list:view',
      'carbon:currency',
      3,
    ],
    [
      'm-payment-create',
      'm-payment',
      'PaymentCreate',
      '录入回款',
      'button',
      '',
      '',
      'payment:create',
      '',
      1,
    ],
    [
      'm-payment-view',
      'm-payment',
      'PaymentView',
      '查看回款',
      'button',
      '',
      '',
      'payment:view',
      '',
      2,
    ],
    [
      'm-payment-confirm',
      'm-payment',
      'PaymentConfirm',
      '确认回款',
      'button',
      '',
      '',
      'payment:confirm',
      '',
      3,
    ],
    [
      'm-payment-reject',
      'm-payment',
      'PaymentReject',
      '驳回回款',
      'button',
      '',
      '',
      'payment:reject',
      '',
      4,
    ],
    [
      'm-payment-void',
      'm-payment',
      'PaymentVoid',
      '回款作废',
      'button',
      '',
      '',
      'payment:void',
      '',
      5,
    ],
  ];
  entries.push(...(businessPermissions as any));
  for (const [
    id,
    pid,
    name,
    title,
    type,
    path,
    component,
    authCode,
    icon,
    sort,
  ] of entries) {
    const existing = systemMenus.find((item) => item.id === id);
    if (!existing) {
      systemMenus.push({
        id,
        pid,
        name,
        title,
        type,
        path,
        component,
        authCode,
        icon,
        status: 1,
        sort,
      });
      changed = true;
    } else if (
      existing.status !== 1 &&
      new Set([
        'm-audit-logs',
        'm-org',
        'm-permissions',
        'm-recycle-bin',
        'm-roles',
        'm-settings',
        'm-system',
        'm-users',
      ]).has(id as string)
    ) {
      existing.status = 1;
      changed = true;
    }
  }
  return changed;
}
